-- Campus Commons: Supabase database + storage setup
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_email text,
  content text not null,
  file_url text,
  file_name text,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;

create policy "Anyone can read posts"
on public.posts for select
to anon, authenticated
using (true);

create policy "Signed-in users can create posts"
on public.posts for insert
to authenticated
with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('campus-uploads', 'campus-uploads', true)
on conflict (id) do nothing;

create policy "Signed-in users can upload campus files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'campus-uploads' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Anyone can view campus uploads"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'campus-uploads');
